application:
    image: jaysde/php-fpm
    tty: true
    ports:
        - 9000:9000
    volumes:
      - .:/var/www
nginx:
    image: jaysde/nginx
    ports:
        - 80:80
    links:
        - application
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
